name = "bt-warriors-roles"
main = "src/index.js"
compatibility_date = "2026-09-19"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.01

[vars]
GUILD_ID = "875130075996094525"
ROLE_ID = "883161380029595689"
